
name: Audit NPM package

# Controls when the workflow will run
on: push

env:
  TOKEN_LISTS_ACTIONS_OR_CI_BUILD: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: brew install librsvg
      - run: npm install -g npm
      - run: npm --version
      - run: npm ci
      - run: npm audit
